### ISSUE TITLE
При попытке повторной регистрации пользователя существующего в системе, подсказка поля email отображается с маленькой буквы

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#1]
1. нажать на кнопку регистрация
2. внести в поле имейла данные сущестующего пользователя

Actual:
подсказка с маленькой буквы
![баг1](https://github.com/user-attachments/assets/b68769d2-1f52-4ccd-85e0-f24e1732a23f)

Expected:
Все подсказки с большой буквы

**Comment by Kostofei** [comment]
Исправлено но на сервере не развернули

**Comment by Santrok** [comment]
Исправлено
