### ISSUE TITLE
В шапке главной страницы приложения элементы "Все разделы", "Поиск по тексту" и "Любое расположение" отображаются с различной жирностью текста

### ISSUE THREAD

**Issue by Halen1986** [KhramtsovaV/StormnetPractise#12]
1. Открыть главную страницу приложения.
2. Найти и развернуть выпадающий список "Любое расположение".

**Comment by Kostofei** [comment]
@Halen1986 Можно пояснить, жирность везде одинаковая 400.

**Comment by Halen1986** [comment]
Тогда вопрос снимается. Сори.
