### ISSUE TITLE
При попытке удаления товара из избранного открывается форма авторизации

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#15]
1. Авторизоваться
2. Добавть товар в избранное
3. Зайти в личный кабинет
4. Открыть Избранное
5. Нажать на звездочку для удаления товара из избранного

Показывается форма авторизация, когда пользователь уже авторизован. При закрытии формы с товара пропадает иконка звезды. При повторном входе в избранное товар остается там

**Comment by Santrok** [comment]
Исправлено, объявление из избранного удаляется корректно. Форма авторизации не открывается
