### ISSUE TITLE
При повторном входе с неправильным Email система указывает что  Email введен неверно

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#19]
Шаги:

1. Перейти на ресурс http://217.197.117.47/
2. Нажать "Вход" в хэдере.
3. Заполнить поля с не валидным Email.
4. Нажать "Войти"

Ожидаемый результат:
Система указывает на ошибку " Неправильно введен Email или Пароль"

Фактический результат:
Система указывает на ошибку "Введите правильный адрес электронной почты".

Priority: Middle

Статус: Новый

Окружение: Windows 10 Version 21H2 Build 19044.1889, Chrome Version 130.0.6723.116 (Official Build) (64-bit)

**Comment by Kostofei** [comment]
Ошибка "Введите правильный адрес электронной почты" возникает если введен не верный формат электронной почты. Пример: nod@gmail

**Comment by Kostofei** [comment]
Текст "Введите правильный адрес электронной почты" исправлен на "Неверный формат электронной почты"

**Comment by Aleh0** [comment]
С позиции безопасности система не должна указывать что конкретно введено неверно. при неверном вводе пароля либо почты обычно делается подсказка "Неправильно введен Email или Пароль".

**Comment by Santrok** [comment]
Исправлено. В случае если поля не заполнены указывается что поля обязательны к заполнению, в остальных случаях "Неправильно введен Email или Пароль"
