### ISSUE TITLE
По нажатию на кнопку восстановить объявления всплывает сообщения об успешном восстановлении, когда объявления не выбраны

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#24]
https://github.com/user-attachments/assets/0feadd01-dcf2-4426-9456-a27d59eea9f8

**Comment by Santrok** [comment]
Исправлено, теперь если объявления не выбраны всплывает сообщение о том что сообщение не выбрано

**Comment by Aleh0** [comment]
Во вкладке "активные" при нажатии "Поместить в архив" ситуация аналогична.

**Comment by Santrok** [comment]
Исправлено
