### ISSUE TITLE
Успешная регистрация пользователей с одинаковыми именами 

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#25]
Шаги:

1. Перейти на сайт по адресу http://217.197.117.47
2. Нажать ссылку "Вход и регистрация" в хэдере сайта.
3. Нажать "Регтстрация".
4. Заполнить поля валидными данными.
5. Нажать "Зарегистрироваться".
6. Вернуться на главную страницу.
7. Выполнить шаги 2и3.
8. Заполнить поле "Контактное лицо" тем же именем как при прошлой регистрации, остальные поля заполнить валидными данными.
9. Повторить пункт 5.

Ожидаемый результат:
Появляется сообщение об ошибке  "Пользователь с таким именем уже существует".

Фактимческий результат:
Появляется окно сообщающее об успешной регистрации.

Priority: middle

Окружение: Windows 11 Version 10.0.22631 Build 22631, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

**Comment by Santrok** [comment]
@Aleh0 У пользователей могут быть одинаковые имена, уникальным полем является Email
