### ISSUE TITLE
После успешного входа зарегистрированного пользователя в хэдере отображается его Email.

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#26]
Шаги:

1. Перейти на сайт по адресу http://217.197.117.47/
2. Проити регистрацию.
3. Осуществить вход.

Ожидаемый реззультат:

В хедере рядом с кнопкой "Выйти" отображается имя пользователя.

Фактимческий результат:
В хедере рядом с кнопкой "Выйти" отображается Email пользователя.

Priority: middle

Окружение: Windows 11 Version 10.0.22631 Build 22631, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

**Comment by Santrok** [comment]
@Aleh0  Воспроизвести ошибку не получилось. Такое возможно если у пользователя не будет заполнено поле контактное лицо. С какой почтой был зарегистрирован пользователь?
