### ISSUE TITLE
При отрицательном значении "id" andpoint (http://217.197.117.47/api/v1/add_to_favorite/) ответ сервера "201 Created" (API)

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#27]
Шаги:
1. В Postman отправить endpoint http://217.197.117.47/api/v1/add_to_favorite/ с отрицательным значением "id" в теле запроса в JSON формате:
{"id": "-36949"}

Ожидаемый результат:
Ответ сервера "400 Bad Request"

Фактический результат:
Ответ сервера "201 Created"

Priority: middle

Окружение: Windows 11 Version 10.0.22631 Build 22631, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

**Comment by Santrok** [comment]
Исправлено, endpoint теперь принимает только положительные значения
