### ISSUE TITLE
Endpoint (http://217.197.117.47/api/v1/create_chat/) не создает чат (API)

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#28]
Шаги:

В Postman отправить endpoint http://217.197.117.47/api/v1/create_chat/ с существующем "id" в теле запроса в JSON формате и текстом сообщения в "text_message":
 {"chat_object": "36916",
"text_message": "Текст сообщения"}.

Ожидаемый результат:
Ответ сервера "201 Created"

Фактический результат:
Ответ сервера "400 Bad Request"

Priority: middle

Окружение: Windows 11 Version 10.0.22631 Build 22631, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

**Comment by Santrok** [comment]
@Aleh0 
тело запроса должно быть в таком виде
{"chat_object": "36916",
"advertisement": "36916",
"text_message": "Текст сообщения"}

**Comment by Aleh0** [comment]
При отправке с пустым body серер отвечал:
{
    "errors": {
        "chat_object": [
            "Обязательное поле."
        ],
        "text_message": [
            "Обязательное поле."
        ]
    }
}
