### ISSUE TITLE
Ответ сервера "201 Created" при отрицательном значении "id" у  endpoint (http://217.197.117.47/api/v1/delete_from_favorite/) (API)

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#29]
Шаги:

1. В Postman отправить endpoint http://217.197.117.47/api/v1/delete_from_favorite/ с отрицательным значением существующего "id" в теле запроса в JSON формате:
{
    "id":"-36949"
}
Ожидаемый результат:
Ответ сервера "400 Bad Request"

Фактический результат:
Ответ сервера "201 Created"

Priority: middle

Окружение: Windows 11 Version 10.0.22631 Build 22631, Chrome Version 130.0.6723.92 (Official Build) (64-bit)

**Comment by Santrok** [comment]
Исправлено, endpoint теперь принимает только положительные значения
