### ISSUE TITLE
Индикатор нажатия на кнопку не покрывает весь элемент

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#3]
воспроизводится на всех кнопках
![баг2](https://github.com/user-attachments/assets/57e20459-c9c2-490f-8166-6567bb3d173c)

**Comment by Santrok** [comment]
Исправлено 
![image](https://github.com/user-attachments/assets/e5fa5061-f010-442d-951c-5edc971a236f)
