### ISSUE TITLE
Нет обозначений обязательности заполнения полей

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#5]
В блоке регистрации поля не обозначены как обязательные к заполнению. 
После оставления любого поля пустым - ошибки
Возможно стоит добавить? Текст или общепринятые иконки?
![баг3](https://github.com/user-attachments/assets/aee1d83f-ab5d-4d44-9bc5-3a42d98a6f19)

**Comment by Santrok** [comment]
Сделан вариант со *
![image](https://github.com/user-attachments/assets/adbfc53e-f848-42c4-97a8-9aef7a3e5e66)
