### ISSUE TITLE
При выборе пункта меню под "Доска объявлений. Беларусь" в хэдере сайта сбрасывается месторасположение по областям в правой части хэдера

### ISSUE THREAD

**Issue by Aleh0** [KhramtsovaV/StormnetPractise#6]
Шаги:

1. Перейти на ресурс http://217.197.117.47/
2. Выбрать место расположения в хэдере.
3. Выбрать раздел меню под "Доска объявлений. Беларусь"

Ожидаемый результат:
Место расположения в хэдере остается.

Фактичечкий результат:
Место расположения в хэдере сбрасывается..

Priority: Middle

Статус: Новый

Окружение: Windows 10 Version 21H2 Build 19044.1889, Chrome Version 130.0.6723.116 (Official Build) (64-bit)

**Comment by Kostofei** [comment]
Не понятно о чем речь, возможно изображение поможет понять баг.

**Comment by Aleh0** [comment]
2. 
![Любое расположение](https://github.com/user-attachments/assets/aeefd84d-118a-4490-a615-0ceb1dafaebe)
3. 
![Доска обьявлений](https://github.com/user-attachments/assets/7d35874d-1806-4fd8-b115-3ef648c4ad0d)

**Comment by Kostofei** [comment]
Данные поля ни как не связанны. При выборе конкретной подкатегории происходит перезагрузка страницы и все поля в форме поиска сбрасываются.
