### ISSUE TITLE
Ошибка при введении разных паролей при регистации не указывает на проблему

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#7]
1. Регистрация
2. В поле пароля ввести Qwerty1
3. В повтор пароля ввести  Qwerty
Actual:  подсказка из чего должен состоять пароль
![баг5](https://github.com/user-attachments/assets/0cf56f0a-73dd-45a5-a016-a99838b0d31b)

Expected: указание пользователю на несовпадение паролей

**Comment by Kostofei** [comment]
![image](https://github.com/user-attachments/assets/4d71d440-a799-4968-85c6-09c1ea84f04a)
В начале пароли проверяются на сложность, а только после на совпадение паролей.
В Qwerty1 семь символов.
