### ISSUE TITLE
Неправильная подсказка о символах в пароле

### ISSUE THREAD

**Issue by KhramtsovaV** [KhramtsovaV/StormnetPractise#8]
Сейчас подсказка:
Пароль должен содержать минимум 8 символов, включать хотя бы одну заглавную букву, одну цифру и один символ нижнего регистра.

А по факту регистрация не проходит без внесения в пароль дну заглавную букву, одну цифру и один символ нижнего регистра и **спец.символа**

**Comment by Kostofei** [comment]
Создал пользователя с паролем 1Qaz2wsx все сработало.
