### ISSUE TITLE
На главной странице в выпадающем списке "Любое расположение" наблюдается несоответствие шрифтов

### ISSUE THREAD

**Issue by Halen1986** [KhramtsovaV/StormnetPractise#9]
1. Открыть приложение и перейти на главную страницу.
2. Найти и развернуть выпадающий список "Любое расположение".

**Comment by Kostofei** [comment]
Если имеется в виду все большими буквами то ток задумано.
![image](https://github.com/user-attachments/assets/b07b7a95-c0ad-41c6-af0c-b5aac36a7378)
Шрифты там одинаковые.

**Comment by Halen1986** [comment]
ок
